#!/bin/sh
#
# This pre-commit hook checks if any versions of clang-format
# are installed, and if so, uses the installed version to format
# the staged changes.

git-clang-format-7 --binary clang-format-7 --extensions cpp,h
